server.forward-headers-strategy: framework
#VERSION: v1
server:
  servlet:
    context-path: /app
#springdoc:
#  api-docs:
#    enabled: true
#    path: '/v3/api-docs'
#  swagger-ui:
#    path: '/swagger-ui'
#    config-url: '/app/v3/api-docs/swagger-config'
#    url: '/app/v3/api-docs'
#    doc-expansion: none
#    disable-swagger-default-url: true