version: "3.9"
services:
  postgres:
    container_name: postgres
    image: "postgres:13.2"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - backend
  keycloak:
    container_name: keycloak
    image: "jboss/keycloak:16.1.1"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    depends_on:
      - "postgres"
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
