---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: public-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        # These are coming from the istio-ingressgateway-certs secret
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        privateKey: /etc/istio/ingressgateway-certs/tls.key
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dremployee
spec:
  host: semployee
  subsets:
    - name: v1
      labels:
        version: "v1"
    - name: v2
      labels:
        version: "v2"
    - name: v3
      labels:
        version: "v3"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vsemployee
spec:
  hosts:
  - "*"
  gateways:
  - public-gateway
  http:
    - match:
        - uri:
            prefix: /app
      route:
        - destination:
            host: semployee.default.svc.cluster.local
            subset: v2
          weight: 80
        - destination:
            host: semployee.default.svc.cluster.local
            subset: v1
          weight: 20
      mirror:
        host: semployee.default.svc.cluster.local
        subset: v3
      mirrorPercentage:
        value: 100.0